- name: Install setuptool and curl
  apt: name={{item}} state=installed
  with_items:
      - python-setuptools
      - curl
      - jq
  update_cache: yes

- name: determine if docker is installed
  shell: which docker
  register: docker_installed
  ignore_errors: true
  changed_when: false

- name: get docker version
  shell: docker --version | awk '{ print $3 }'
  register: docker_installed_version
  when: docker_installed is success
  changed_when: false

- name: install or upgrade docker
  shell: curl https://releases.rancher.com/install-docker/{{ docker_version }}.sh | sh
  when: not docker_installed is success or
        not docker_installed_version.stdout|search(docker_version|string)

- name: upgrade pip (Ubuntu)
  pip: name=pip state=latest
  when: ansible_os_family == "Debian" and not ansible_distribution == "Debian"

- name: install additional dependencies (pip)
  pip: name=docker-py state=present
  tags: pip

- name: make sure docker is running
  service: name=docker state=started enabled=true